### PR TITLE
adds responsiveness

### PR DESCRIPTION
**Pull request by saintaze**
I have added responsiveness!

- I have added media queries at the very end of the CSS file under `/* MEDIA QUERIES */`

- Responsiveness is down to `280px` width screen which covers almost all cell phones.

### CODE REVIEW

**Comment by JVJplus** [comment]
great work with grids!
btw I noticed the logo is hidding on smaller size, is it part of ux or some bug?

**Review by JVJplus — COMMENTED** [review]
merged

**Review by JVJplus — COMMENTED** [review]
merged

**Comment by JVJplus** [comment]
thanks!

**Comment by saintaze** [comment]
> btw I noticed the logo is hidding on smaller size, is it part of ux or some bug?

It's not a bug, I am doing that as part of responsiveness and hiding the logo on small screens. On extra small screen sizes, it's good practice to hide unnecessary details such as logo and only keep the most important things, like the search bar and bookmark which serves some functionality.

**Pull request merged**
